# Generated by Django 5.2.15 on 2026-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_monument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
