# Generated by Django 5.2.15 on 2026-06-17 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фото галереї', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='monument',
            options={'ordering': ['order', 'id'], 'verbose_name': "Пам'ятник", 'verbose_name_plural': "Пам'ятники"},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Короткий опис зображення для SEO та доступності.', max_length=255, verbose_name='Alt-текст для фото'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активне'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='monument',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Короткий опис зображення для SEO та доступності.', max_length=255, verbose_name='Alt-текст для фото'),
        ),
        migrations.AddField(
            model_name='monument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='monument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_subtitle',
            field=models.CharField(blank=True, help_text='Наприклад: Зателефонуйте нам — допоможемо підібрати памʼятник.', max_length=255, verbose_name='CTA підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(blank=True, help_text='Наприклад: Потрібна консультація?', max_length=255, verbose_name='CTA заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_display',
            field=models.CharField(blank=True, help_text='Формат для сайту, наприклад: +38 (067) 123-45-67', max_length=50, verbose_name='Телефон для відображення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='viber',
            field=models.URLField(blank=True, help_text='Повне посилання на Viber.', verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monuments', to='core.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='image',
            field=models.ImageField(upload_to='monuments/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок першого екрану'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок першого екрану'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(help_text='Формат для tel:, наприклад: +380671234567', max_length=30, verbose_name='Телефон для посилання'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, help_text='Повне посилання, наприклад: https://t.me/username', verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Повне посилання, наприклад: https://wa.me/380671234567', verbose_name='WhatsApp'),
        ),
    ]
