# Generated by Django 5.2.15 on 2026-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_contactrequest_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Відео галереї', 'verbose_name_plural': 'Відео галерея'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='poster',
            field=models.ImageField(blank=True, help_text='Необовʼязково. Показується як превʼю до запуску відео.', null=True, upload_to='gallery/posters/', verbose_name='Обкладинка відео'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва відео'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(default=1, help_text='Рекомендований формат: MP4.', upload_to='gallery/videos/', verbose_name='Відео'),
            preserve_default=False,
        ),
    ]
