# Generated by Django 5.2.15 on 2026-06-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gallery_options_remove_gallery_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, help_text='Рекомендований формат: MP4.', upload_to='gallery/videos/', verbose_name='Відео'),
        ),
    ]
