# Generated by Django 5.2.15 on 2026-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_facebook_sitesettings_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Заповнюй, якщо для памʼятника є фіксована ціна.', null=True, verbose_name='Точна ціна, грн'),
        ),
        migrations.AddField(
            model_name='monument',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, help_text='Мінімальна ціна, якщо вартість залежить від комплектації.', null=True, verbose_name='Ціна від, грн'),
        ),
        migrations.AddField(
            model_name='monument',
            name='price_to',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальна орієнтовна ціна. Необовʼязково.', null=True, verbose_name='Ціна до, грн'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Повне посилання на TikTok.', verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Повне посилання на Facebook.', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Повне посилання на Instagram.', verbose_name='Instagram'),
        ),
    ]
