# Generated by Django 5.2.15 on 2026-06-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_monument_price_monument_price_from_monument_price_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='price',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='price_to',
        ),
        migrations.AddField(
            model_name='category',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, help_text='Стартова ціна для всієї категорії. Наприклад: 18000', null=True, verbose_name='Ціна від, грн'),
        ),
    ]
