# Generated by Django 5.2.15 on 2026-06-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_monument_price_remove_monument_price_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, help_text='Повне посилання, наприклад: https://t.me/username', max_length=255, verbose_name='Telegram'),
        ),
    ]
