# Generated by Django 5.2.15 on 2026-06-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sitesettings_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, help_text='Повне посилання, наприклад: https://t.me/username', verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='viber',
            field=models.CharField(blank=True, help_text='Повне посилання на Viber.', max_length=255, verbose_name='Viber'),
        ),
    ]
