# Generated by Django 5.2.15 on 2026-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_telegram_alter_sitesettings_viber'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='section',
            field=models.CharField(choices=[('process', 'Процес'), ('works', 'Наші роботи')], default='process', max_length=20, verbose_name='Секція'),
        ),
    ]
