# Generated by Django 5.2.15 on 2026-07-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_advantage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('tag', models.CharField(default='Про компанію', max_length=100, verbose_name='Мітка секції')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text_1', models.TextField(verbose_name='Перший абзац')),
                ('text_2', models.TextField(blank=True, verbose_name='Другий абзац')),
                ('text_3', models.TextField(blank=True, verbose_name='Третій абзац')),
                ('card_kicker', models.CharField(max_length=150, verbose_name='Мітка картки')),
                ('card_title', models.CharField(max_length=255, verbose_name='Заголовок картки')),
                ('card_description', models.TextField(verbose_name='Опис картки')),
                ('image', models.ImageField(blank=True, help_text='Наприклад, карта України або інше зображення для лівої картки.', upload_to='about/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Блок про компанію',
                'verbose_name_plural': 'Блок про компанію',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('value', models.CharField(help_text='Наприклад: 10+, 500+', max_length=50, verbose_name='Значення')),
                ('label', models.CharField(help_text='Наприклад: років досвіду', max_length=150, verbose_name='Підпис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.aboutsection', verbose_name='Блок про компанію')),
            ],
            options={
                'verbose_name': 'Статистика про компанію',
                'verbose_name_plural': 'Статистика про компанію',
                'ordering': ['order', 'id'],
            },
        ),
    ]
