# Generated by Django 5.2.15 on 2026-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aboutsection_aboutstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('section_type', models.CharField(choices=[('process', 'Процес'), ('works', 'Наші роботи')], max_length=20, unique=True, verbose_name='Тип секції')),
                ('tag', models.CharField(max_length=100, verbose_name='Мітка секції')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Заголовок галереї',
                'verbose_name_plural': 'Заголовки галерей',
                'ordering': ['section_type'],
            },
        ),
    ]
