# Generated by Django 5.2.15 on 2026-07-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gallerysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('tag', models.CharField(default='Каталог', max_length=100, verbose_name='Мітка секції')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('default_price_from', models.PositiveIntegerField(default=9000, help_text="Показується у вкладці 'Всі'. Наприклад: 9000", verbose_name='Загальна ціна від')),
                ('price_hint', models.CharField(default='Натисніть «Замовити» для уточнення всіх деталей', max_length=255, verbose_name='Підказка під ціною')),
                ('price_on_request_text', models.CharField(default='Ціна уточнюється', max_length=100, verbose_name='Текст, якщо ціна не вказана')),
                ('empty_category_text', models.CharField(default='Товар відсутній', max_length=150, verbose_name='Текст порожньої категорії')),
                ('empty_catalog_text', models.CharField(default='Каталог буде наповнений найближчим часом.', max_length=150, verbose_name='Текст порожнього каталогу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Блок каталогу',
                'verbose_name_plural': 'Блок каталогу',
            },
        ),
    ]
