# Generated by Django 5.2.15 on 2026-07-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_catalogsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_subtitle',
            field=models.CharField(default='Збережіть памʼять про найрідніших', max_length=150, verbose_name='Підпис біля логотипу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 NOVOGRANKOR. Усі права захищено.', max_length=150, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_button_text',
            field=models.CharField(default='Отримати безкоштовний прорахунок', max_length=100, verbose_name='Текст основної CTA-кнопки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_viber_button_text',
            field=models.CharField(default='Звʼязатися в Viber', max_length=100, verbose_name='Текст Viber-кнопки в CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='Виготовлення та встановлення памʼятників з натурального граніту по всій Україні.', verbose_name='Опис у футері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_slogan',
            field=models.CharField(default='Збережіть памʼять про найрідніших', max_length=150, verbose_name='Слоган у футері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(default='● Виготовлення та встановлення по всій Україні', max_length=150, verbose_name='Мітка Hero-блоку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_viber_button_text',
            field=models.CharField(default='Написати в Viber', max_length=100, verbose_name='Текст кнопки Viber у Hero'),
        ),
    ]
