# Generated by Django 5.2.15 on 2026-07-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesettings_brand_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'Блок «Про компанію»', 'verbose_name_plural': 'Блок «Про компанію»'},
        ),
        migrations.AlterModelOptions(
            name='aboutstat',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Статистика блоку «Про компанію»', 'verbose_name_plural': 'Статистика блоку «Про компанію»'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['section', 'order', 'id'], 'verbose_name': 'Відео галереї', 'verbose_name_plural': 'Відео галерея'},
        ),
        migrations.AlterModelOptions(
            name='monument',
            options={'ordering': ['category__order', 'order', 'id'], 'verbose_name': "Пам'ятник", 'verbose_name_plural': "Пам'ятники"},
        ),
    ]
