# Generated by Django 5.2.15 on 2026-08-03 08:50

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_aboutsection_options_alter_aboutstat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=core.fields.WebPImageField(blank=True, help_text='Наприклад, карта України або інше зображення для лівої картки.', upload_to='about/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='poster',
            field=core.fields.WebPImageField(blank=True, help_text='Необовʼязково. Показується як превʼю до запуску відео.', null=True, upload_to='gallery/posters/', verbose_name='Обкладинка відео'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='image',
            field=core.fields.WebPImageField(upload_to='monuments/', verbose_name='Фото'),
        ),
    ]
